Schead completed
AntonKozlov/os226-2020 pull request #28
Opened 2020-10-08 16:41 UTC by toxakaz

Schead completed

2020-10-08 16:42 UTC, toxakaz commented
Не могу понять, как сделать корректный pull request

2020-10-11 18:39 UTC, AntonKozlov commented
rebase это вы зря, я теперь не вижу только ваших изменений. Можно вылечить как 
* `git reset --hard 65435b3b44e62139091b5204697d556297098bf0` -- откатиться к моему коммиту
* `git checkout cf9efeb29df65d37d1e974b88b00dba475b21ad6 -- .` -- взять полностью содержимое вашего коммита
* `git commit ...`
* Аккуратно просмотреть, что всё на месте и `git push origin +HEAD` -- пушнуть бранч, возможно перезатирая remote коммиты

2020-10-11 19:54 UTC, AntonKozlov requested changes
Есть технические проблемы вроде креша. Вы можете смотреть на прогон тестов локально или в своём форке: https://github.com/toxakaz/os226-2020/actions/runs/295871058

2020-10-11 19:54 UTC, AntonKozlov commented on sched.c
> +	while (((struct task*)binary_heap_view_top(heap))->timeout <= 0)
Здесь возникает исключение
```
Starting program: /home/anton/stuff/os226-2020/main < test/cosched/1.in
        coapp_rt id 1 cnt 10
        coapp_rt id 2 cnt 10

Program received signal SIGSEGV, Segmentation fault.
sched_time_elapsed (amount=1) at sched.c:49
49              while (((struct task*)binary_heap_view_top(heap))->timeout <= 0)
(gdb) bt
#0  sched_time_elapsed (amount=1) at sched.c:49
#1  0x00005555555557a6 in coapp_rt (_ctx=0x5555555590e8 <app_ctxs+8>) at apps.c:110
#2  0x00005555555562a3 in sched_time_elapsed (amount=1) at sched.c:52
#3  0x00005555555557a6 in coapp_rt (_ctx=0x5555555590e4 <app_ctxs+4>) at apps.c:110
#4  0x00005555555562a3 in sched_time_elapsed (amount=0) at sched.c:52
#5  0x00005555555564ce in sched_run () at sched.c:124
#6  0x000055555555590f in cosched (argc=1, argv=0x7fffffffdcf0) at apps.c:135
#7  0x00005555555554c9 in exec (argc=1, argv=0x7fffffffdcf0) at apps.c:49
#8  0x0000555555555a4b in shell (argc=1, argv=0x7fffffffe610) at apps.c:165
#9  0x0000555555555afb in init () at apps.c:175
#10 0x000055555555538a in main (argc=1, argv=0x7fffffffe7e8) at main.c:41
```
это маскируется обработчиком исключения ...

2020-10-11 19:54 UTC, AntonKozlov commented on main.c
> +	}
... закомментируйте установку обработчика, и попробуйте запустить

2020-10-11 19:54 UTC, AntonKozlov commented on sched.c
> +		active_tasks[i]->timeout -= amount;
Обычно ожидающие задачи не включают в очередь на исполнение -- они не смогут быть исполнены, так зачем их сортировать? А здесь вам приходится обновлять все элементы кучи.

Логичнее было бы иметь отдельную кучу для ожидающих, с сортировкой по времени срабатывания -- тогда вы бы могли ограничиться просмотром только верхних _ожидающих_, без прохода по всем или ожидающим задачам.

Я вижу обновление таймаута в задачах, но не вижу обновление порядка в очереди после этого

2020-10-11 19:54 UTC, AntonKozlov commented on sched.c
> +		active_task->entry(active_task->ctx);
Вы запускаете задачи прямо на месте? Но ведь текущая задача ещё не кончилась. Мы определяли кооперативный планировщик как выполняющий задачи от начала до конца. А если задача имеет вид?
```
static void coapp_rt(void *_ctx) {
        struct coapp_ctx *ctx = _ctx;

        printf("%16s id %d cnt %d\n", __func__, ctx - app_ctxs, ctx->cnt);

        sched_time_elapsed(1);

        if (0 < ctx->cnt) {
                sched_cont(coapp_rt, ctx, 0);
        }

        --ctx->cnt;
       printf("done");
}
```

Вероятно из-за этого, 4 тест ведёт себя странно
```
anton@tornado:~/stuff/os226-2020$ ./main < test/cosched/4.in 
      coapp_task id 1 cnt 4
```
А должно быть
```
anton@tornado:~/stuff/os226-2020$ cat test/cosched/4.out 
      coapp_task id 1 cnt 4
        coapp_rt id 2 cnt 16
        coapp_rt id 2 cnt 15
      coapp_task id 1 cnt 3
        coapp_rt id 2 cnt 14
        coapp_rt id 2 cnt 13
      coapp_task id 1 cnt 2
        coapp_rt id 2 cnt 12
        coapp_rt id 2 cnt 11
      coapp_task id 1 cnt 1
        coapp_rt id 2 cnt 10
        coapp_rt id 2 cnt 9
      coapp_task id 1 cnt 0
        coapp_rt id 2 cnt 8
        coapp_rt id 2 cnt 7
        coapp_rt id 2 cnt 6
        coapp_rt id 2 cnt 5
        coapp_rt id 2 cnt 4
        coapp_rt id 2 cnt 3
        coapp_rt id 2 cnt 2
        coapp_rt id 2 cnt 1
        coapp_rt id 2 cnt 0
```

2020-10-11 21:15 UTC, toxakaz commented on sched.c
> +		active_tasks[i]->timeout -= amount;
От того, что таймаут всех задач изменится на константу, результат сортировки не изменится, думал я, пока не задумался получше

2020-10-18 11:15 UTC, AntonKozlov commented
Вы не пытались исправить? Закрываю пока с partial

2020-10-18 11:15 UTC, closed without merging