Update main.c
AntonKozlov/os226-2020 pull request #5
Opened 2020-09-14 17:22 UTC by Krekep

Первый раз таким занимаюсь, надеюсь всё правильно делаю.

2020-09-15 08:53 UTC, AntonKozlov requested changes
Все замечания исправлять не обязательно.

Критическая проблема одна: сейчас решение зависает https://github.com/AntonKozlov/os226-2020/pull/5/checks?check_run_id=1113512336. Кажется вы неправильно обрабатываете результат `getchar`

2020-09-15 08:53 UTC, AntonKozlov commented on main.c
>  }
Выглядит идентично `echo`, но должна выводить код ошибки

2020-09-15 08:53 UTC, AntonKozlov commented on main.c
> +
для конвертации `snprintf` будет проще, понятнее и возможно быстрее

2020-09-15 08:53 UTC, AntonKozlov commented on main.c
> +    char* result = (char*)malloc(sizeof(char) * (n + 1));
Выделение памяти -- операция с известными накладными расходами и проблемами с управлением (нужно читать код, чтобы убедиться что этот блок был освобождён)

2020-09-15 08:53 UTC, AntonKozlov commented on main.c
> +                char retcodeName[] = { 'r', 'e', 't', 'c', 'o', 'd', 'e' };
`char *echoName = "echo";` -- та же строка, только с `\0` терминатором. Терминатор позволяет использовать функции вроде `strcmp`

2020-09-15 08:53 UTC, AntonKozlov commented on main.c
> +            if (isRetcode)
`else if` было бы правильнее логически

2020-09-15 08:53 UTC, AntonKozlov commented on main.c
> +    char** input = (char**)malloc(sizeof(char*) * 16);
массив фиксированной длины небольшого размера, резоннее использовать массив на стеке
`char *input[16]`

2020-09-15 08:53 UTC, AntonKozlov commented on main.c
> +    {
Судя по этому коду, вы зачитываете полностью весь ввод. Он может быть большим. Правильнее читать и обрабатывать по строчкам

2020-09-15 08:53 UTC, AntonKozlov commented on main.c
> +    while (c != '\0')
**!**: `getchar` возвращает `EOF` когда ввод заканчивается. EOF часто кодируется -1, которое не равно 0 (как здесь

2020-09-16 09:24 UTC, Krekep commented on main.c
>  }
Какой код ошибки? Код возврата предыдущей функции? Этот код возврата выводится, просто я свёл функцию retcode к функции echo

2020-09-16 09:27 UTC, Krekep commented on main.c
> +    char** input = (char**)malloc(sizeof(char*) * 16);
Тут я руководствовался тем, что пользователи могут вводить странные вещи, длинной превышающей 16 (условно). Просто массив объявленный с помощью [] не расширить, если ввод в него не помещается

2020-09-16 09:28 UTC, Krekep commented on main.c
> +    {
Я считываю посимвольно, пока не встретиться символ перевода строки или ';', т.е. пока идут аргументы у команды. Потом обрабатываю команду с аргументами и начинаю всё с начала (только читаю с места, где остановился в прошлый раз)

2020-09-16 09:35 UTC, Krekep commented
Если это не на полный балл, то хотелось бы получить новую порцию замечаний)

2020-09-17 17:21 UTC, AntonKozlov commented on main.c
> +    char** input = (char**)malloc(sizeof(char*) * 16);
А, вижу `realloc`

2020-09-17 17:21 UTC, AntonKozlov commented on main.c
> +                input[countArgs] = (char*)malloc(sizeof(char) * 12);
Ну здесь-то точно лучше массив :)

2020-09-17 17:21 UTC, AntonKozlov commented on main.c
>  }
А, вижу

2020-09-17 17:22 UTC, AntonKozlov commented
Выглядит нормально

2020-09-17 17:22 UTC, closed without merging